[SPARK_APP_CONFIGS]
spark.app.name=Hello Spark
spark.master=local[3]
spark.driver.extraJavaOptions=-Dlog4j.configuration=file:log4j.properties -Dlogfile.name=hello-spark -Dspark.yarn.app.container.log.dir=app-logs
spark.sql.shuffle.partitions = 2