"""Initial database schema

Revision ID: 0e77dc7ab39a
Revises: 
Create Date: 2025-07-28 12:40:24.650104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e77dc7ab39a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's unique email address for login"),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's display name"),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Whether user has verified their email'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.Column('bio', sa.Text(), nullable=True, comment="User's biography or description"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this record'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When this record was deleted (NULL if active)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Team name or title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Team description and purpose'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether team is active'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created this team'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When this record was deleted (NULL if active)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_updated_at'), ['updated_at'], unique=False)

    op.create_table('projects',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Project name or title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Project description and goals'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether project is active'),
    sa.Column('team_id', sa.UUID(), nullable=True, comment='Team that owns this project'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created this project'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When this record was deleted (NULL if active)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_updated_at'), ['updated_at'], unique=False)

    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False, comment='Team this membership belongs to'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who is a member'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='teamrole'), nullable=False, comment="Member's role in the team"),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When user joined the team'),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True, comment='When user left the team (NULL if active)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this record'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When this record was deleted (NULL if active)'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Task title or summary'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed task description'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False, comment='Task priority level'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='When this task is due'),
    sa.Column('completed', sa.Boolean(), nullable=False, comment='Whether task is completed'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When task was marked as completed'),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='Project containing this task'),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='User assigned to this task'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created this task'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When this record was deleted (NULL if active)'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_updated_at'), ['updated_at'], unique=False)

    op.create_table('task_attachments',
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename as uploaded by user'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='UUID-based filename for storage'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type of the file'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the file'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When file was uploaded'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this attachment belongs to'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this record'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When this record was deleted (NULL if active)'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_attachments_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_attachments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_attachments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_attachments_stored_filename'), ['stored_filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_task_attachments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_attachments_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_attachments_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('task_comments',
    sa.Column('content', sa.Text(), nullable=False, comment='Comment text content'),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True, comment='When comment was last edited (NULL if never edited)'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task this comment belongs to'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who wrote this comment'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this record'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When this record was deleted (NULL if active)'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_task_comments_created_by'))
        batch_op.drop_index(batch_op.f('ix_task_comments_created_at'))

    op.drop_table('task_comments')
    with op.batch_alter_table('task_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_attachments_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_stored_filename'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_created_by'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_created_at'))
        batch_op.drop_index(batch_op.f('ix_task_attachments_content_type'))

    op.drop_table('task_attachments')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_by'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_completed'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to'))

    op.drop_table('tasks')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_updated_at'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_role'))
        batch_op.drop_index(batch_op.f('ix_team_members_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_team_members_created_by'))
        batch_op.drop_index(batch_op.f('ix_team_members_created_at'))

    op.drop_table('team_members')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_updated_at'))
        batch_op.drop_index(batch_op.f('ix_projects_title'))
        batch_op.drop_index(batch_op.f('ix_projects_team_id'))
        batch_op.drop_index(batch_op.f('ix_projects_is_active'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_projects_created_by'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_updated_at'))
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_is_active'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))
        batch_op.drop_index(batch_op.f('ix_teams_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_teams_created_by'))
        batch_op.drop_index(batch_op.f('ix_teams_created_at'))

    op.drop_table('teams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_created_by'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
