"""Add role column to users

Revision ID: f49d78274f94
Revises: daa59265cea2
Create Date: 2025-07-28 15:29:54.873004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49d78274f94'
down_revision: Union[str, None] = 'daa59265cea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'role',
            sa.String(length=32),
            nullable=False,
            server_default='user',  # Set default for existing rows
            comment='Role of the user (admin, user, guest, etc.)'
        ))
    # Optionally remove the default so future inserts must specify or use ORM default
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
