export const programmingLanguages = [
  "TypeScript",
  "JavaScript",
  "CSS",
  "LESS",
  "SCSS",
  "JSON",
  "HTML",
  "XML",
  "PHP",
  "C#",
  "C++",
  "Razor",
  "Markdown",
  "Diff",
  "Java",
  "VB",
  "CoffeeScript",
  "Handlebars",
  "Batch",
  "Pug",
  "F#",
  "Lua",
  "Powershell",
  "Python",
  "Ruby",
  "SASS",
  "R",
  "Objective-C",
];

export const optionsProgrammingLanguage = programmingLanguages.map(
  (language) => ({
    label: language,
    value: language.toLowerCase(),
  })
);

// export const monacoThemesList: Record<string, string> = {
//   active4d: "Active4D",
//   "all-hallows-eve": "All Hallows Eve",
//   amy: "Amy",
//   "birds-of-paradise": "Birds of Paradise",
//   blackboard: "Blackboard",
//   "brilliance-black": "Brilliance Black",
//   "brilliance-dull": "Brilliance Dull",
//   "chrome-devtools": "Chrome DevTools",
//   "clouds-midnight": "Clouds Midnight",
//   clouds: "Clouds",
//   cobalt: "Cobalt",
//   dawn: "Dawn",
//   dreamweaver: "Dreamweaver",
//   eiffel: "Eiffel",
//   "espresso-libre": "Espresso Libre",
//   github: "GitHub",
//   idle: "IDLE",
//   katzenmilch: "Katzenmilch",
//   "kuroir-theme": "Kuroir Theme",
//   lazy: "LAZY",
//   "magicwb--amiga-": "MagicWB (Amiga)",
//   "merbivore-soft": "Merbivore Soft",
//   merbivore: "Merbivore",
//   "monokai-bright": "Monokai Bright",
//   monokai: "Monokai",
//   "night-owl": "Night Owl",
//   "oceanic-next": "Oceanic Next",
//   "pastels-on-dark": "Pastels on Dark",
//   "slush-and-poppies": "Slush and Poppies",
//   "solarized-dark": "Solarized-dark",
//   "solarized-light": "Solarized-light",
//   spacecadet: "SpaceCadet",
//   sunburst: "Sunburst",
//   "textmate--mac-classic-": "Textmate (Mac Classic)",
//   "tomorrow-night-blue": "Tomorrow-Night-Blue",
//   "tomorrow-night-bright": "Tomorrow-Night-Bright",
//   "tomorrow-night-eighties": "Tomorrow-Night-Eighties",
//   "tomorrow-night": "Tomorrow-Night",
//   tomorrow: "Tomorrow",
//   twilight: "Twilight",
//   "upstream-sunburst": "Upstream Sunburst",
//   "vibrant-ink": "Vibrant Ink",
//   "xcode-default": "Xcode_default",
//   zenburnesque: "Zenburnesque",
//   iplastic: "iPlastic",
//   idlefingers: "idleFingers",
//   krtheme: "krTheme",
//   monoindustrial: "monoindustrial",
// };

export const monacoThemesList: Record<string, Promise<any>> = {
  "vs-dark": import("monaco-themes/themes/Active4D.json"),
  light: import("monaco-themes/themes/Active4D.json"),
  active4d: import("monaco-themes/themes/Active4D.json"),
  "all-hallows-eve": import("monaco-themes/themes/All Hallows Eve.json"),
  amy: import("monaco-themes/themes/Amy.json"),
  "birds-of-paradise": import("monaco-themes/themes/Birds of Paradise.json"),
  blackboard: import("monaco-themes/themes/Blackboard.json"),
  "brilliance-black": import("monaco-themes/themes/Brilliance Black.json"),
  "brilliance-dull": import("monaco-themes/themes/Brilliance Dull.json"),
  "chrome-devtools": import("monaco-themes/themes/Chrome DevTools.json"),
  "clouds-midnight": import("monaco-themes/themes/Clouds Midnight.json"),
  clouds: import("monaco-themes/themes/Clouds.json"),
  cobalt: import("monaco-themes/themes/Cobalt.json"),
  cobalt2: import("monaco-themes/themes/Cobalt2.json"),
  dawn: import("monaco-themes/themes/Dawn.json"),
  dracula: import("monaco-themes/themes/Dracula.json"),
  dreamweaver: import("monaco-themes/themes/Dreamweaver.json"),
  eiffel: import("monaco-themes/themes/Eiffel.json"),
  "espresso-libre": import("monaco-themes/themes/Espresso Libre.json"),
  "github-dark": import("monaco-themes/themes/GitHub Dark.json"),
  "github-light": import("monaco-themes/themes/GitHub Light.json"),
  github: import("monaco-themes/themes/GitHub.json"),
  idle: import("monaco-themes/themes/IDLE.json"),
  katzenmilch: import("monaco-themes/themes/Katzenmilch.json"),
  "kuroir-theme": import("monaco-themes/themes/Kuroir Theme.json"),
  lazy: import("monaco-themes/themes/LAZY.json"),
  "magicwb--amiga-": import("monaco-themes/themes/MagicWB (Amiga).json"),
  "merbivore-soft": import("monaco-themes/themes/Merbivore Soft.json"),
  merbivore: import("monaco-themes/themes/Merbivore.json"),
  "monokai-bright": import("monaco-themes/themes/Monokai Bright.json"),
  monokai: import("monaco-themes/themes/Monokai.json"),
  "night-owl": import("monaco-themes/themes/Night Owl.json"),
  nord: import("monaco-themes/themes/Nord.json"),
  "oceanic-next": import("monaco-themes/themes/Oceanic Next.json"),
  "pastels-on-dark": import("monaco-themes/themes/Pastels on Dark.json"),
  "slush-and-poppies": import("monaco-themes/themes/Slush and Poppies.json"),
  "solarized-dark": import("monaco-themes/themes/Solarized-dark.json"),
  "solarized-light": import("monaco-themes/themes/Solarized-light.json"),
  spacecadet: import("monaco-themes/themes/SpaceCadet.json"),
  sunburst: import("monaco-themes/themes/Sunburst.json"),
  "textmate--mac-classic-": import(
    "monaco-themes/themes/Textmate (Mac Classic).json"
  ),
  "tomorrow-night-blue": import(
    "monaco-themes/themes/Tomorrow-Night-Blue.json"
  ),
  "tomorrow-night-bright": import(
    "monaco-themes/themes/Tomorrow-Night-Bright.json"
  ),
  "tomorrow-night-eighties": import(
    "monaco-themes/themes/Tomorrow-Night-Eighties.json"
  ),
  "tomorrow-night": import("monaco-themes/themes/Tomorrow-Night.json"),
  tomorrow: import("monaco-themes/themes/Tomorrow.json"),
  twilight: import("monaco-themes/themes/Twilight.json"),
  "upstream-sunburst": import("monaco-themes/themes/Upstream Sunburst.json"),
  "vibrant-ink": import("monaco-themes/themes/Vibrant Ink.json"),
  "xcode-default": import("monaco-themes/themes/Xcode_default.json"),
  zenburnesque: import("monaco-themes/themes/Zenburnesque.json"),
  iplastic: import("monaco-themes/themes/iPlastic.json"),
  idlefingers: import("monaco-themes/themes/idleFingers.json"),
  krtheme: import("monaco-themes/themes/krTheme.json"),
  monoindustrial: import("monaco-themes/themes/monoindustrial.json"),
};
