export const programmingLanguages = [
    "TypeScript",
    "JavaScript",
    "CSS",
    "LESS",
    "SCSS",
    "JSON",
    "HTML",
    "XML",
    "PHP",
    "C#",
    "C++",
    "Razor",
    "Markdown",
    "Diff",
    "Java",
    "VB",
    "CoffeeScript",
    "Handlebars",
    "Batch",
    "Pug",
    "F#",
    "Lua",
    "Powershell",
    "Python",
    "Ruby",
    "SASS",
    "R",
    "Objective-C",
  ];
  
  export const optionsProgrammingLanguage = programmingLanguages.map((language) => ({
    label: language,
    value: language.toLowerCase(),
  }));